import fs from 'node:fs/promises';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
export async function createDemo(dir){
  try{await fs.access(path.join(dir,'.git'));return;}catch{}
  await fs.mkdir(dir,{recursive:true});
  const run=(args,env={})=>{const p=spawnSync('git',args,{cwd:dir,env:{...process.env,...env},encoding:'utf8'});if(p.status)throw Error(p.stderr);return p.stdout.trim();};
  run(['init','-b','main']);run(['config','user.name','Alex Morgan']);run(['config','user.email','alex@example.test']);
  await fs.mkdir(path.join(dir,'src','renderer'),{recursive:true});await fs.mkdir(path.join(dir,'src','components'),{recursive:true});await fs.mkdir(path.join(dir,'tests'),{recursive:true});await fs.mkdir(path.join(dir,'docs'),{recursive:true});
  const commit=(message,days,author='Alex Morgan')=>{run(['add','.']);const timestamp=new Date(Date.now()-days*86400000).toISOString();run(['commit','-m',message],{GIT_AUTHOR_DATE:timestamp,GIT_COMMITTER_DATE:timestamp,GIT_AUTHOR_NAME:author,GIT_AUTHOR_EMAIL:author.toLowerCase().replace(' ','.')+'@example.test'});};
  await fs.writeFile(path.join(dir,'README.md'),'# Horizon\n\nA small, local-first rendering toolkit.\n\n## Development\n\nOpen index.html in your browser.\n');
  await fs.writeFile(path.join(dir,'.gitignore'),'node_modules/\ndist/\n.DS_Store\n');await fs.writeFile(path.join(dir,'package.json'),JSON.stringify({name:'horizon',version:'0.8.0',type:'module',scripts:{test:'node --test'}},null,2)+'\n');commit('chore: initialize the Horizon workspace',26);
  await fs.writeFile(path.join(dir,'src','renderer','pipeline.js'),`/** A minimal rendering pipeline. */\nexport class RenderPipeline {\n  constructor(device) {\n    this.device = device;\n    this.frameCount = 0;\n    this.dirty = true;\n  }\n\n  render(scene) {\n    const encoder = this.device.createCommandEncoder();\n    const pass = encoder.beginRenderPass(scene.descriptor);\n    pass.setPipeline(scene.pipeline);\n    pass.draw(scene.vertexCount);\n    pass.end();\n    this.device.queue.submit([encoder.finish()]);\n    this.frameCount++;\n  }\n\n  invalidate() {\n    this.dirty = true;\n  }\n}\n`);commit('feat: introduce the rendering pipeline',24);
  await fs.writeFile(path.join(dir,'src','components','toolbar.js'),`export function toolbar(actions) {\n  const root = document.createElement('nav');\n  root.className = 'toolbar';\n  for (const action of actions) {\n    const button = document.createElement('button');\n    button.textContent = action.label;\n    button.addEventListener('click', action.run);\n    root.append(button);\n  }\n  return root;\n}\n`);commit('feat: add keyboard-friendly toolbar',22,'Jordan Lee');
  run(['branch','feature/command-menu']);
  await fs.writeFile(path.join(dir,'src','tokens.css'),':root {\n  --surface: #12151c;\n  --accent: #a395f7;\n  --radius: 8px;\n  --space: 8px;\n}\n');commit('design: establish the graphite color system',21,'Sam Rivera');
  run(['switch','feature/command-menu']);await fs.writeFile(path.join(dir,'src','components','command-menu.js'),`export const commands = [\n  { id: 'open', label: 'Open workspace', shortcut: 'Mod+O' },\n  { id: 'search', label: 'Search everything', shortcut: 'Mod+K' },\n];\n\nexport function filterCommands(query) {\n  return commands.filter(command =>\n    command.label.toLowerCase().includes(query.toLowerCase())\n  );\n}\n`);commit('feat: searchable command menu with fuzzy matching',19,'Jordan Lee');
  await fs.writeFile(path.join(dir,'tests','commands.test.js'),`import {test} from 'node:test';\nimport {strict as assert} from 'node:assert';\nimport {filterCommands} from '../src/components/command-menu.js';\ntest('filters commands', () => assert.equal(filterCommands('Open').length, 1));\n`);commit('test: cover command discovery and filtering',18,'Jordan Lee');
  run(['switch','main']);await fs.writeFile(path.join(dir,'docs','accessibility.md'),'# Accessibility\n\nAll actions must support keyboard navigation.\nKeep code selectable and screen-reader friendly.\n');commit('docs: document accessibility expectations',17,'Sam Rivera');
  run(['merge','--no-ff','feature/command-menu','-m','Merge command menu into main']);run(['tag','v0.8.0']);
  run(['switch','-c','fix/resize-observer']);await fs.writeFile(path.join(dir,'src','renderer','resize.js'),`export function observeViewport(element, callback) {\n  const observer = new ResizeObserver(entries => {\n    const {width, height} = entries[0].contentRect;\n    callback({width, height, ratio: devicePixelRatio});\n  });\n  observer.observe(element);\n  return () => observer.disconnect();\n}\n`);commit('fix: respect device pixel ratio on viewport resize',12,'Sam Rivera');
  run(['switch','main']);await fs.writeFile(path.join(dir,'docs','performance.md'),'# Performance budget\n\nRender only what is visible.\nRe-use GPU buffers between frames.\nAvoid allocating objects in the animation loop.\n');commit('docs: define viewport rendering budgets',11);
  run(['merge','--no-ff','fix/resize-observer','-m','Merge viewport resize improvements']);run(['tag','v0.9.0']);
  run(['switch','-c','feature/webgpu-renderer']);
  await fs.writeFile(path.join(dir,'src','renderer','buffer-pool.js'),`export class BufferPool {\n  constructor(device) {\n    this.device = device;\n    this.buffers = new Map();\n  }\n\n  acquire(key, size, usage) {\n    const current = this.buffers.get(key);\n    if (current && current.size >= size) return current;\n    current?.destroy();\n    const buffer = this.device.createBuffer({size, usage});\n    this.buffers.set(key, buffer);\n    return buffer;\n  }\n\n  dispose() {\n    for (const buffer of this.buffers.values()) buffer.destroy();\n    this.buffers.clear();\n  }\n}\n`);commit('feat: add reusable GPU buffer pool',6);
  await fs.writeFile(path.join(dir,'tests','renderer.test.js'),`import {test} from 'node:test';\nimport {strict as assert} from 'node:assert';\ntest('viewport dimensions are positive', () => assert.ok(1280 > 0));\n`);commit('test: validate renderer viewport assumptions',4,'Jordan Lee');
  await fs.appendFile(path.join(dir,'docs','performance.md'),'\n## Allocation strategy\n\nGrow buffers geometrically to amortize allocation cost.\n');commit('perf: document geometric buffer growth',2);
  const p=path.join(dir,'src','renderer','pipeline.js');let source=await fs.readFile(p,'utf8');source=source.replace('    this.dirty = true;','    this.dirty = true;\n    this.enableCulling = true;');source=source.replace('    const encoder = this.device.createCommandEncoder();','    if (!this.dirty) return;\n\n    const visible = scene.filterVisible(this.enableCulling);\n    const encoder = this.device.createCommandEncoder({\n      label: "horizon-frame",\n    });');source=source.replace('    pass.draw(scene.vertexCount);','    for (const batch of visible.batches) {\n      pass.setVertexBuffer(0, batch.buffer);\n      pass.draw(batch.vertexCount, batch.instanceCount);\n    }');source=source.replace('    this.frameCount++;','    this.frameCount++;\n    this.dirty = false;');await fs.writeFile(p,source);
  await fs.appendFile(path.join(dir,'src','tokens.css'),'\n[data-theme="light"] {\n  --surface: #ffffff;\n  --accent: #725bc9;\n}\n');run(['add','src/tokens.css']);
  await fs.writeFile(path.join(dir,'src','renderer','visibility.js'),`export function intersects(a, b) {\n  return a.x < b.x + b.width &&\n    a.x + a.width > b.x &&\n    a.y < b.y + b.height &&\n    a.y + a.height > b.y;\n}\n`);
  await fs.appendFile(path.join(dir,'README.md'),'\n## WebGPU\n\nThe new renderer batches visible geometry and reuses GPU buffers.\n');
}
